name: Generate website
on:
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: generate
    cancel-in-progress: true

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2


            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1.7


            # We set up a folder that Pluto can use to cache exported notebooks. If the notebook file did not change, then Pluto can take the exported file from cache instead of running the notebook.
            - name: ⏱ Cache notebook states
              uses: actions/cache@v2
              with:
                  path: _cache
                  key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}-${{ hashFiles('**/*jl') }}
                  restore-keys: |
                      ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml', '.github/workflows/*' ) }}


            - name: ⏱ Cache .julia
              uses: actions/cache@v2
              with:
                path: ~/.julia
                key: ${{ runner.os }}-dotjulia-v1-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-dotjulia-v1

            - name: 🪴 Generate site
              run: |
                julia -e 'using Pkg
                  Pkg.activate(mktempdir())
                  Pkg.add([
                    # this is only the version used to run the generate notebook, not the version used to generate exports...
                    Pkg.PackageSpec(name="Pluto", version="0.18"),
                  ])

                  include("generate.jl")'
            
            - uses: actions/upload-artifact@v2
              if: always()
              with:
                path: generation_report.html

            - name: 🚀 Deploy to dist
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: dist
                  FOLDER: _site
